// priority: 0

console.info('Hello, World! (You will only see this line once in console, during startup)')

onEvent('item.registry', event => {
	// Register new items here
	// event.create('example_item').displayName('Example Item')
})

onEvent('block.registry', event => {
    event.create('matrix')
        .material('rock')
        .hardness(0.5)
        .displayName('Matrix')
        .renderType('cutout')
        .notSolid()
        .textureAll('kubejs:block/matrix')
        .model('kubejs:block/matrix')
        .box(2, 2, 2, 14, 14, 14)
    event.create('pillar_ne')
        .material('rock')
        .hardness(0.5)
        .displayName('Pillar')
        .renderType('cutout')
        .box(0, 0, 0, 16, 32, 16)
    event.create('pillar_nw')
        .material('rock')
        .hardness(0.5)
        .displayName('Pillar')
        .renderType('cutout')
        .box(0, 0, 0, 16, 32, 16)
    event.create('pillar_se')
        .material('rock')
        .hardness(0.5)
        .displayName('Pillar')
        .renderType('cutout')
        .box(0, 0, 0, 16, 32, 16)
    event.create('pillar_sw')
        .material('rock')
        .hardness(0.5)
        .displayName('Pillar')
        .renderType('cutout')
        .box(0, 0, 0, 16, 32, 16)
})

onEvent('fluid.registry', event => {
    event.create('perditio_essentia')
    .thinTexture(0x403E3E)
    .bucketColor(0x403E3E)
    .displayName('Perditio')
    event.create('terra_essentia')
    .thinTexture(0x20AB20)
    .bucketColor(0x20AB20)
    .displayName('Terra')
})