
[worldgen]

	[worldgen.soulstone]
		#Should soulstone ore generate on the surface?
		generateSurfaceSoulstone = true
		#Minimum height at which surface soulstone ore can spawn.
		surfaceSoulstoneMinY = 60
		#Size of soulstone ore veins underground.
		soulstoneSize = 12
		#Size of soulstone ore veins on the surface.
		surfaceSoulstoneSize = 6
		#Minimum height at which soulstone ore can spawn.
		soulstoneMinY = -64
		#Should soulstone ore generate underground?
		generateSoulstone = true
		#Maximum height at which surface soulstone ore can spawn.
		surfaceSoulstoneMaxY = 100
		#Amount of soulstone ore veins.
		soulstoneAmount = 8
		#Maximum height at which soulstone ore can spawn.
		soulstoneMaxY = 30
		#Amount of soulstone ore veins on the surface.
		surfaceSoulstoneAmount = 5

	[worldgen.brilliance]
		#Minimum height at which brilliant stone can spawn.
		brilliantStoneMinY = -64
		#Maximum height at which brilliant stone can spawn.
		brilliantStoneMaxY = 40
		#Should brilliant stone generate?
		generateBrilliantStone = true
		#Amount of brilliant stone veins.
		brilliantStoneSize = 4

	[worldgen.runewood]
		#Chance for runewood trees to generate in open biomes such as plains.
		#Range: 0.0 ~ 1.0
		runewoodCommonChance = 0.02
		#Should runewood trees naturally generate?
		generateRunewood = true
		#Chance for runewood trees to generate in forest biomes.
		#Range: 0.0 ~ 1.0
		runewoodRareChance = 0.01

	[worldgen.blazing_quartz]
		#Should blaze quartz ore generate?
		generateBlazeQuartz = true
		#Size of blaze quartz ore veins.
		blazeQuartzSize = 16

[spirit]

	[spirit.repair]
		#If set to true, malum will allow you to repair any item using spirit focusing with the default repair data.
		defaultRepairIfMissing = true

	[spirit.affinity]

		[spirit.affinity.soul_ward]
			#Multiplier for physical damage taken while soul ward is active.
			#Range: 0.0 ~ 1.0
			soulWardPhysical = 0.699999988079071
			#Multiplier for magic damage taken while soul ward is active.
			#Range: 0.0 ~ 1.0
			soulWardMagic = 0.10000000149011612
			#Base time in ticks it takes for one point of soul ward to recover.
			soulWardRate = 60

		[spirit.affinity.heart_of_stone]
			#Base time in ticks it takes for one point of heart of stone to recover.
			heartOfStoneRate = 40
			#Amount of hunger consumed when recovering a point of heart of stone. Do note that this will only matter if the player has the earthen affinity.
			#Range: 0.0 ~ 1.0
			heartOfStoneCost = 0.2

	[spirit.spawner]
		#If set to true, mob spawners will create soulless mobs instead.
		lameSpawners = false

[item]

	[item.rebound]
		#If set to true, you may put rebound on any weapon in the game.
		enableUltimateRebound = false

